version: "3.8"

services:
  wordpress:
    build: .
    container_name: usagcd_net_wordpress
    restart: always
    ports:
      - "8082:80"
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${DB_TABLE_PREFIX}
    depends_on:
      - db
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:5.7
    container_name: usagcd_net_db
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
