name: CI/CD for WordPress

on:
  push:
    branches:
      - master # Trigger workflow when code is pushed to the dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
            registry: hub.radioactive.ac
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t hub.radioactive.ac/radioactive/usagcd-org:main .
          docker push hub.radioactive.ac/radioactive/usagcd-org:main

      - name: Trigger Portainer Webhook
        run: |
          curl -k -X POST https://5.181.83.200:9443/api/stacks/webhooks/884ce927-33ec-46f2-95b9-8a844713f160
        env:
          CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt

      - name: Set up SSH  
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host production-server\n  HostName ${{ secrets.PRODUCTION_HOST }}\n  User ${{ secrets.PRODUCTION_USER }}\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Import Database via SSH
        run: |
          # Copy the latest usagcd-net-db-dump.sql to the production server
          scp -i ~/.ssh/id_rsa usagcd-net-db-dump.sql production-server:/tmp/usagcd-net-db-dump.sql

          # Import the database on the production server
          ssh -i ~/.ssh/id_rsa production-server "mysql -h10.4.30.2 -u hdbWeejb -pIdGWusgagbSzHZLfYBrb wp_JWjkK < /tmp/usagcd-net-db-dump.sql"
